urls.py
from django.conf.urls import url
from . import views

app_name = 'gamefy'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^register/$', views.registration_view, name='register'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^game/$', views.game_view, name='game'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^scoreboard/$', views.score_board_view, name='scoreboard'),
    url(r'^404/$', views.error_view, name='error-404'),
    url(r'^delete_gamer/$', views.delete_gamer_view, name='delete_gamer'),
]

models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Gamer(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    game_one_score = models.IntegerField()

    def __str__(self):
        return self.user

class Game(models.Model):
    game_name = models.CharField(max_length=50)
    game_detail = models.CharField(max_length=200)
    game_best_score = models.CharField(max_length=10)
    game_best_scorer = models.CharField(max_length=50)

    def __str__(self):
        return self.game_name+' - '+self.game_best_score+' - '+self.game_best_scorer

forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            # authenticate that the user is exist
            user = authenticate(username=username, password=password)

            if not user:  # if does not give a user model object
                raise forms.ValidationError('User does not exist')

            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')

            if not user.is_active:
                raise forms.ValidationError('User is no longer active')

        return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password2']

    # check if two passwords matched or not
    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password != password2:
            raise forms.ValidationError('Password must match!')

        return password

    # check if username already registered or not
    def clean_username(self):
        username = self.cleaned_data.get('username')
        username_qs = User.objects.filter(username=username)

        if username_qs.exists():
            raise forms.ValidationError('This username is not available!')
        else:
            return username

    # check if email already registered or not
    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_qs = User.objects.filter(email=email)

        if email_qs.exists():
            raise forms.ValidationError('This email has already been registered!')
        else:
            return email

views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, UserLoginForm
from .models import Game, Gamer, User
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)
from django.contrib.auth.decorators import login_required

def index_view(request):
    return render(request, 'gamefy/index.html')

def registration_view(request):
    logout(request)#logged out if already login

    form = UserRegistrationForm(request.POST or None)

    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        #user.set_password is built in method for User model, otherwise pass wont be saved
        user.set_password(password)
        user.save()
        return redirect('gamefy:login')

    context = {'form':form, 'title':'User Registration', 'submit':'Register'}
    return render(request, 'gamefy/form.html', context)

def login_view(request):
    next = request.GET.get('next')#for login_requied page, mendatory

    form = UserLoginForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = authenticate(username=username, password=password)
        login(request, user)
        if next:#for login_required page, mendatory
            return redirect(next)

        return redirect('gamefy:game')

    # for login_required page, login form message, optional
    context = {'form':form, 'title':'Login Form', 'submit':'Login', 'log_require_message':'You must be logged in!'}
    if next:
        return render(request, 'gamefy/form.html', context)

    context = {'form': form, 'title': 'Login Form', 'submit': 'Login'}
    return render(request, 'gamefy/form.html', context)

def logout_view(request):
    logout(request)
    return redirect('gamefy:index')

@login_required(login_url='/gamefy/login')
def game_view(request):
    found_gamer_obj = Gamer.objects.filter(user=request.user)

    if request.method == 'POST':
        score = request.POST.get('score')
        print(score)

        if not found_gamer_obj:
            gamer_obj = Gamer(user=request.user, game_one_score=score)
            gamer_obj.save()
        else:
            gamer_obj = Gamer.objects.get(user=request.user)
            gamer_obj.game_one_score=score
            gamer_obj.save()

    previous_score = None
    if found_gamer_obj:
        previous_score = Gamer.objects.get(user=request.user).game_one_score
    else:
        previous_score = 1000#1000 is just an assumed highest value to compare high score

    return render(request, 'gamefy/games.html', {'previous_score':previous_score})

def profile_view(request):
    if request.user.is_authenticated():
        found_current_gamer_list_for_score = Gamer.objects.filter(user=request.user)
        # if gamer played at least once and made a score which is saved
        if found_current_gamer_list_for_score:
            context = {'gamer':found_current_gamer_list_for_score[0]}
            return render(request, 'gamefy/profile.html', context)
        else:
            return render(request, 'gamefy/profile.html')

    #if try to manually enter the profile without having loggedin
    return redirect('gamefy:error-404')

@login_required(login_url='/gamefy/login/')
def score_board_view(request):
    all_gamer_objrcts_list = Gamer.objects.all().order_by('game_one_score');
    context = {'all_gamers': all_gamer_objrcts_list}
    return render(request, 'gamefy/scoreboard.html', context)

def error_view(request):
    return render(request, 'gamefy/404.html')

def delete_gamer_view(request):
    try:
        to_be_deleted_user = User.objects.get(username=request.user)
        to_be_deleted_user.delete()

        print(to_be_deleted_user, 'deleted')

    except User.DoesNotExist:
        print('error1')
        return redirect('gamefy:index')

    except Exception as e:
        print('error2')
        return redirect('gamefy:index')

    return redirect('gamefy:index')

templates/gamefy/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}GameFy{% endblock %}</title>

    {% load staticfiles %}

    <!--css files-->
    <link href="{% static 'gamefy/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'gamefy/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'gamefy/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'gamefy/css/style.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-TH-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'gamefy:index' %}">Home</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-TH-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="#">
                    <a href="{% url 'gamefy:game' %}">Play Games</span></a>
                </li>
                <li>
                    <a href="{% url 'gamefy:scoreboard' %}">Scoreboard</a>
                </li>
            </ul>
            <!--
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search games" method="get" action="#">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form>
            -->
            <ul class="nav navbar-nav navbar-right">

                {% block login_logout_user_area %}
                    <!--if user is not logged in, then must show register and login icons-->
                    {% if not user.is_authenticated %}
                        <li>
                            <a href="{% url 'gamefy:register' %}">
                                <span class="glyphicon glyphicon-plus"></span> Register</a>
                        </li>
                        <li>
                            <a href="{% url 'gamefy:login' %}">
                                <span class="glyphicon glyphicon-log-in"></span> Login</a>
                        </li>
                    <!-- otherwise must show profile and logout icon icon-->
                    {% else %}
                        <li>
                            <a href="{% url 'gamefy:profile' %}">
                                <span class="glyphicon glyphicon-user"></span> {{user.username}}</a>
                        </li>
                        <li>
                            <a href="{% url 'gamefy:logout' %}">
                                <span class="glyphicon glyphicon-log-out"></span> Logout</a>
                        </li>
                    {% endif %}

                {% endblock %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav><!-- end of navbar-default -->

<!--body content inside block body-->
{% block body %}
{% endblock %}

<!--java scripts-->
<script src="{% static 'gamefy/js/jquery.min.js' %}"></script>
<script src="{% static 'gamefy/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/gamefy/form.html
{% extends 'gamefy/base.html' %}
{% block title %}User Registration{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-xs-1">
                </div>
                <div class="col-md-6 col-xs-10">
                    <p class="text-danger">{{log_require_message}}</p>
                    <h3>{{title}}</h3>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% for field in form %}
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <span class="text-danger small">{{ field.errors }}</span>
                                    </div>
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <span class="text-danger small">{{ field.messages}}</span>
                                    </div>
                                    <label class="control-label col-sm-4">{{ field.label_tag }}</label>
                                    <div class="col-sm-8">{{ field }}</div>
                                </div>
                                {% endfor %}

                                <div class="form-group">
                                    <div class="col-sm-offset-4 col-sm-8">
                                        <button type="submit" class="btn btn-default">{{submit}}</button>
                                    </div>
                                </div>
                            </form>
                        </div><!--end of panel-body-->
                    </div><!--end of panel-->
                </div>
                <div class="col-md-3 col-xs-1">
                </div>
            </div><!--end of row-->
        </div><!--end of container-->
    </div>
</div>
{% endblock %}

templates/gamefy/games.html
{% extends 'gamefy/base.html' %}
{% load staticfiles %}

<!--if user is logged in then must show profile and logout icons
instead of register and login icons-->
{% block login_logout_user_area %}
<li>
    <a href="{% url 'gamefy:profile' %}">
        <span class="glyphicon glyphicon-user"></span> {{user.username}}</a>
</li>
<li>
    <a href="{% url 'gamefy:logout' %}">
        <span class="glyphicon glyphicon-log-out"></span> Logout</a>
</li>
{% endblock %}

<!--profile page body for logged in user-->
{% block body %}

<script src="{% static 'gamefy/js/game.js' %}"></script>

<div class="container-fluid">
    <div class="row">
        <div class="container">

            <div class="row">
                <div class="col-md-4">
                    <h3 class="text-primary">Games List:</h3>

                    <ol type="I" style="font-size:1.2em" class="bg-info">
                        <li>
                            <a href="{% url 'gamefy:game' %}">
                                <button class="btn btn-default" style="width:100%; text-align:left">Guess the number</button>
                            </a>
                        </li>
                    </ol>
                </div>

                <div class="col-md-8 panel panel-default">
                    <h4  id="game_notifications" class="bg-info" style="padding: 10px;">Guess a number between 0 and 50.</h4>
                    <h4  id="success_message" class="bg-success" style="padding: 10px;"></h4>
                    <br>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="number"
                                   style="font-weight: bold; font-size: 1.2em; width: 80%;padding: 8px 20px;margin: 5px 0;box-sizing: border-box;"
                                   id="user_input" name="Input" placeholder="Your number here">
                            <br>
                            <button onclick="checkInputAndResponse({{ previous_score }})"
                                    style="width: 80%;padding: 8px 20px;margin: 5px 0;box-sizing: border-box;"
                                    class="btn btn-success">Submit your guess</button>
                            <br><br><br>
                            <button onclick="restartGame()"
                                    style="width: 80%;padding: 8px 20px;margin: 5px 0;box-sizing: border-box;"
                                    class="btn btn-warning">Restart</button>
                        </div><!--end of first col-->

                        <div class="col-md-6 bg-warning">
                            <h4 class="text-success">Hint:</h4>
                            <table class="table table-bordered">
                                <tr >
                                    <th>Make your guess:</th>
                                </tr>
                                <tr class="bg-warning">
                                    <td id="game_hint"></td>
                                </tr>
                            </table>
                            <h4>Score:</h4>
                            <table class="table table-bordered">
                                <tr>
                                    <th>Times you have tried:</th>
                                </tr>
                                <tr>
                                    <td id="game_tries" style="font-weight: bold; font-size: 18px;">0</td>
                                </tr>
                            </table>
                        </div><!--end of second col-->

                    </div><!--end of row-->
                </div>

            </div><!--end of row-->
        </div><!--end of container-->
    </div>
</div>
<script>
function saveBestScore(tries_number){
    $.ajax({
        url: '{% url "gamefy:game" %}',
        method: 'POST',
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            'score': tries_number,
        },
        success : function(data){
            //alert("Score saved");
        },
        error : function (data) {
             alert("error, while saving score!");
        }
    });
}
</script>
{% endblock %}

templates/gamefy/index.html
{% extends 'gamefy/base.html' %}

<!--home body // for all visitors-->
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="container">
            <h1 class="text-center text-danger">GameFy</h1>>
            <div class="row">
                <div class="col-md-6 panel panel-default">
                    <h3 class="text-warning text-center">About GameFy</h3>
                    <p class="text-info" style="font-size:1.3em">GameFy is a free Web apps for the gamers that allows them
                        to play online logic games.</p>
                    <br>
                </div>
                <div class="col-md-6 panel panel-default">
                    <h3 class="text-info">GameFy features:</h3>
                    <ol type="I" class="text-warning" style="font-size:1.3em">
                        <li>Gamer registration for personal account.</li>
                        <li>Playing amazing different online logic games.</li>
                        <li>Personal dashboard.</li>
                        <li>Updated scoreboard to compare brain speed.</li>
                    </ol>
                    <br>
                    <h3 class="text-info">Used technologies:</h3>
                    <ul class="list-group" style="font-size:1.2em">
                        <li class="list-group-item">Django & Python</li>
                        <li class="list-group-item">Javascript</li>
                        <li class="list-group-item">Bootstrap</li>
                    </ul>
                </div>
            </div><!--end of row-->
        </div><!--end of container-->
    </div>
</div>
{% endblock %}

templates/gamefy/profile.html
{% extends 'gamefy/base.html' %}

<!--if user is logged in then must show profile and logout icons
instead of register and login icons-->
{% block login_logout_user_area %}
<li>
    <a href="{% url 'gamefy:profile' %}">
        <span class="glyphicon glyphicon-user"></span> {{user.username}}</a>
</li>
<li>
    <a href="{% url 'gamefy:logout' %}">
        <span class="glyphicon glyphicon-log-out"></span> Logout</a>
</li>
{% endblock %}

<!--profile page body for logged in user-->
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="container">
            <div class="row">
                <div class="col-md-8 panel panel-default">
                    <h3 class="text-primary">Your scoreboard:</h3>
                    <table class="table table-bordered">
                        <tr class="bg-info text-warning">
                            <th>Username</th>
                            <th>Game one score (number of try)</th>
                        </tr>
                        <tr class="bg-warning text-primary">
                            <td>{{ gamer.user }}</td>
                            <td>{{ gamer.game_one_score }}</td>
                        </tr>
                    </table>
                    <br><br>
                </div>
                <div class="col-md-4 panel panel-default text-center">
                    <br>
                    <a href="{% url 'gamefy:delete_gamer' %}">
                        <button class="btn btn-danger">Delete Your Account</button></a>
                    <br><br>
                    <p class="text-info"><strong>Be careful!</strong> if you press this <strong>Red button</strong>,
                        you will not get a chance to be confirmed and your account as a gamer will be deleted permanently.</p>
                    <br>
                </div>
            </div><!--end of row-->
        </div><!--end of container-->
    </div>
</div>
{% endblock %}

templates/gamefy/scoreboard.html
{% extends 'gamefy/base.html' %}

<!--if user is logged in then must show profile and logout icons
instead of register and login icons-->
{% block login_logout_user_area %}
<li>
    <a href="{% url 'gamefy:profile' %}">
        <span class="glyphicon glyphicon-user"></span> {{user.username}}</a>
</li>
<li>
    <a href="{% url 'gamefy:logout' %}">
        <span class="glyphicon glyphicon-log-out"></span> Logout</a>
</li>
{% endblock %}

<!--scoreboard body for logged in user-->
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="container panel panel-default">

            <h3 class="text-primary">Gamers scoreboard:</h3>
            <table class="table table-bordered">
                <tr class="bg-info text-warning">
                    <th>Gamer's ID</th>
                    <th>Game one score (number of try)</th>
                </tr>
                {% for gamer in all_gamers %}
                <tr class="bg-warning text-primary">
                    <td>{{ gamer.user }}</td>
                    <td>{{ gamer.game_one_score }}</td>
                </tr>
                {% endfor %}
            </table>
            <br>
        </div><!--end of container-->
    </div>
</div>
{% endblock %}